---
#- name: upgrade all packages
#  yum:
#    name: '*'
#    state: latest

- name: installing kvm virtualization host
  command: yum groupinstall -y "Virtualization Host"

- name: install required packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - "{{ pkgs }}"

- name: restarting libvirtd
  service:
    name: libvirtd
    state: started
    enabled: yes

- name: configuring kvm
  lineinfile:
    path: /etc/modprobe.d/kvm-nested.conf
    state: present
    create: yes
    line: "{{ item.line }}"
  with_items:
  - { line: "options kvm-intel nested=1" }
  - { line: "options kvm-intel enable_shadow_vmcs=1" }
  - { line: "options kvm-intel enable_apicv=1" }
  - { line: "options kvm-intel ept=1" }

- shell: modprobe -r kvm_intel
- shell: modprobe -a kvm_intel
